services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "admin123"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "http"
      - key: TZ
        value: "America/New_York"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"